import type { DeviceModel, DeviceId, DeviceCategory } from '@/types'

const MAC_CAM = {
  front:     [0,  7, 20] as [number,number,number],
  isometric: [11, 9, 17] as [number,number,number],
  side:      [22, 9,  9] as [number,number,number],
}
const TABLET_CAM = {
  front:     [0, 0, 22] as [number,number,number],
  isometric: [9, 5, 18] as [number,number,number],
  side:      [22, 3, 10] as [number,number,number],
}
const WATCH_CAM = {
  front:     [0, 0, 14] as [number,number,number],
  isometric: [5, 3, 12] as [number,number,number],
  side:      [14, 2,  6] as [number,number,number],
}

type RawDevice = Omit<DeviceModel, 'gltfPath' | 'thumbnailPath'> & { id: DeviceId }

const DEVICES: DeviceModel[] = [
  // ── iPhones ──────────────────────────────────────────────────────────────────
  {
    id: 'iphone-16-pro',
    name: 'iPhone 16 Pro',
    category: 'iphone',
    gltfPath: '/models/iphone-16-pro.gltf',
    thumbnailPath: '/thumbnails/iphone-16-pro.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'natural',  label: 'Natural Titanium',  hex: '#c8b89a' },
      { id: 'black',    label: 'Black Titanium',     hex: '#2c2c2e' },
      { id: 'white',    label: 'White Titanium',     hex: '#e8e4de' },
      { id: 'desert',   label: 'Desert Titanium',    hex: '#c5a882' },
    ],
  },
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    category: 'iphone',
    gltfPath: '/models/iphone-15-pro.gltf',
    thumbnailPath: '/thumbnails/iphone-15-pro.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.4577,
    colors: [
      { id: 'natural', label: 'Natural Titanium', hex: '#c8b89a' },
      { id: 'black',   label: 'Black Titanium',   hex: '#2c2c2e' },
      { id: 'white',   label: 'White Titanium',   hex: '#e8e4de' },
      { id: 'blue',    label: 'Blue Titanium',     hex: '#4a6b8c' },
    ],
  },
  {
    id: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    category: 'iphone',
    gltfPath: '/models/iphone-15-pro-max.gltf',
    thumbnailPath: '/thumbnails/iphone-15-pro-max.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.4577,
    colors: [
      { id: 'natural', label: 'Natural Titanium', hex: '#c8b89a' },
      { id: 'black',   label: 'Black Titanium',   hex: '#2c2c2e' },
      { id: 'white',   label: 'White Titanium',   hex: '#e8e4de' },
      { id: 'blue',    label: 'Blue Titanium',     hex: '#4a6b8c' },
    ],
  },
  {
    id: 'iphone-15',
    name: 'iPhone 15',
    category: 'iphone',
    gltfPath: '/models/iphone-15.gltf',
    thumbnailPath: '/thumbnails/iphone-15.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.4577,
    colors: [
      { id: 'black',  label: 'Black',  hex: '#1c1c1e' },
      { id: 'blue',   label: 'Blue',   hex: '#4a90a4' },
      { id: 'green',  label: 'Green',  hex: '#5a8a6a' },
      { id: 'yellow', label: 'Yellow', hex: '#f5e066' },
      { id: 'pink',   label: 'Pink',   hex: '#f4a7b9' },
    ],
  },
  {
    id: 'iphone-15-plus',
    name: 'iPhone 15 Plus',
    category: 'iphone',
    gltfPath: '/models/iphone-15-plus.gltf',
    thumbnailPath: '/thumbnails/iphone-15-plus.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.4577,
    colors: [
      { id: 'black',  label: 'Black',  hex: '#1c1c1e' },
      { id: 'blue',   label: 'Blue',   hex: '#4a90a4' },
      { id: 'green',  label: 'Green',  hex: '#5a8a6a' },
      { id: 'yellow', label: 'Yellow', hex: '#f5e066' },
      { id: 'pink',   label: 'Pink',   hex: '#f4a7b9' },
    ],
  },
  {
    id: 'iphone-14-pro',
    name: 'iPhone 14 Pro',
    category: 'iphone',
    gltfPath: '/models/iphone-14-pro.gltf',
    thumbnailPath: '/thumbnails/iphone-14-pro.png',
    screenAspect: 19.5 / 9,
    modelScale: 45.777,
    colors: [
      { id: 'space',  label: 'Space Black',  hex: '#1c1c1e' },
      { id: 'silver', label: 'Silver',        hex: '#e8e4de' },
      { id: 'gold',   label: 'Gold',          hex: '#f5e6c8' },
      { id: 'purple', label: 'Deep Purple',   hex: '#4a3d6b' },
    ],
  },
  {
    id: 'iphone-13-pro-max',
    name: 'iPhone 13 Pro Max',
    category: 'iphone',
    gltfPath: '/models/iphone-13-pro-max.gltf',
    thumbnailPath: '/thumbnails/iphone-13-pro-max.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'graphite', label: 'Graphite',    hex: '#3a3a3c' },
      { id: 'gold',     label: 'Gold',        hex: '#f5e6c8' },
      { id: 'silver',   label: 'Silver',      hex: '#e8e4de' },
      { id: 'sierra',   label: 'Sierra Blue', hex: '#8fa8c0' },
      { id: 'alpine',   label: 'Alpine Green',hex: '#4a7a5a' },
    ],
  },
  {
    id: 'iphone-13',
    name: 'iPhone 13',
    category: 'iphone',
    gltfPath: '/models/iphone-13.gltf',
    thumbnailPath: '/thumbnails/iphone-13.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'midnight',  label: 'Midnight',  hex: '#1c1c1e' },
      { id: 'starlight', label: 'Starlight', hex: '#f5f0e8' },
      { id: 'blue',      label: 'Blue',      hex: '#2d5a8e' },
      { id: 'pink',      label: 'Pink',      hex: '#f4a7b9' },
      { id: 'green',     label: 'Green',     hex: '#4a7a5a' },
      { id: 'red',       label: 'Red',       hex: '#e02020' },
    ],
  },
  {
    id: 'iphone-13-mini',
    name: 'iPhone 13 mini',
    category: 'iphone',
    gltfPath: '/models/iphone-13-mini.gltf',
    thumbnailPath: '/thumbnails/iphone-13-mini.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'midnight',  label: 'Midnight',  hex: '#1c1c1e' },
      { id: 'starlight', label: 'Starlight', hex: '#f5f0e8' },
      { id: 'blue',      label: 'Blue',      hex: '#2d5a8e' },
      { id: 'pink',      label: 'Pink',      hex: '#f4a7b9' },
      { id: 'green',     label: 'Green',     hex: '#4a7a5a' },
      { id: 'red',       label: 'Red',       hex: '#e02020' },
    ],
  },
  {
    id: 'iphone-12-pro-bezel-less',
    name: 'iPhone 12 Pro (Bezel-less)',
    category: 'iphone',
    gltfPath: '/models/iphone-12-pro-bezel-less.gltf',
    thumbnailPath: '/thumbnails/iphone-12-pro-bezel-less.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'graphite', label: 'Graphite', hex: '#3a3a3c' },
      { id: 'silver',   label: 'Silver',   hex: '#e8e4de' },
      { id: 'gold',     label: 'Gold',     hex: '#f5e6c8' },
      { id: 'blue',     label: 'Blue',     hex: '#2d5a8e' },
    ],
  },
  {
    id: 'iphone-12-2020',
    name: 'iPhone 12 (2020)',
    category: 'iphone',
    gltfPath: '/models/iphone-12-2020.gltf',
    thumbnailPath: '/thumbnails/iphone-12-2020.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'black',  label: 'Black',  hex: '#1c1c1e' },
      { id: 'white',  label: 'White',  hex: '#f5f0e8' },
      { id: 'red',    label: 'Red',    hex: '#e02020' },
      { id: 'green',  label: 'Green',  hex: '#4a7a5a' },
      { id: 'blue',   label: 'Blue',   hex: '#2d5a8e' },
      { id: 'purple', label: 'Purple', hex: '#6a3d8a' },
    ],
  },
  {
    id: 'pro-max-notchless',
    name: 'Pro Max Notchless',
    category: 'iphone',
    gltfPath: '/models/pro-max-notchless.gltf',
    thumbnailPath: '/thumbnails/pro-max-notchless.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'black',   label: 'Black',          hex: '#1c1c1e' },
      { id: 'silver',  label: 'Silver',          hex: '#e8e4de' },
      { id: 'natural', label: 'Natural Titanium',hex: '#c8b89a' },
    ],
  },

  // ── iPads ─────────────────────────────────────────────────────────────────────
  {
    id: 'ipad-mini-6',
    name: 'iPad mini 6',
    category: 'ipad',
    gltfPath: '/models/ipad-mini-6.gltf',
    thumbnailPath: '/thumbnails/ipad-mini-6.png',
    screenAspect: 3 / 2,
    modelScale: 3.5,
    camPresets: TABLET_CAM,
    colors: [
      { id: 'space',     label: 'Space Gray', hex: '#2c2c2e' },
      { id: 'starlight', label: 'Starlight',  hex: '#f5f0e8' },
      { id: 'pink',      label: 'Pink',       hex: '#f4a7b9' },
      { id: 'purple',    label: 'Purple',     hex: '#6a3d8a' },
    ],
  },
  {
    id: 'ipad-2021-magic-keyboard',
    name: 'iPad 2021 + Magic Keyboard',
    category: 'ipad',
    gltfPath: '/models/ipad-2021-magic-keyboard.gltf',
    thumbnailPath: '/thumbnails/ipad-2021-magic-keyboard.png',
    screenAspect: 4 / 3,
    modelScale: 22.76,
    camPresets: MAC_CAM,
    colors: [
      { id: 'space',     label: 'Space Gray', hex: '#2c2c2e' },
      { id: 'silver',    label: 'Silver',     hex: '#e8e4de' },
    ],
  },
  {
    id: 'generic-tablet',
    name: 'Generic Tablet',
    category: 'ipad',
    gltfPath: '/models/generic-tablet.gltf',
    thumbnailPath: '/thumbnails/generic-tablet.png',
    screenAspect: 4 / 3,
    modelScale: 0.1157,
    camPresets: TABLET_CAM,
    colors: [
      { id: 'black', label: 'Black', hex: '#1c1c1e' },
      { id: 'white', label: 'White', hex: '#f5f0e8' },
    ],
  },
  {
    id: 'infinity-tablet',
    name: 'Infinity Tablet',
    category: 'ipad',
    gltfPath: '/models/infinity-tablet.gltf',
    thumbnailPath: '/thumbnails/infinity-tablet.png',
    screenAspect: 4 / 3,
    modelScale: 0.1157,
    camPresets: TABLET_CAM,
    colors: [
      { id: 'black', label: 'Black', hex: '#1c1c1e' },
      { id: 'white', label: 'White', hex: '#f5f0e8' },
    ],
  },

  // ── Macs ──────────────────────────────────────────────────────────────────────
  {
    id: 'macbook-pro-m3-16',
    name: 'MacBook Pro M3 16"',
    category: 'mac',
    gltfPath: '/models/macbook-pro-m3-16.gltf',
    thumbnailPath: '/thumbnails/macbook-pro-m3-16.png',
    screenAspect: 16 / 10,
    modelScale: 0.2322,
    camPresets: MAC_CAM,
    colors: [
      { id: 'space',  label: 'Space Black', hex: '#1c1c1e' },
      { id: 'silver', label: 'Silver',      hex: '#e8e4de' },
    ],
  },
  {
    id: 'macbook-pro-m3-14',
    name: 'MacBook Pro M3 14"',
    category: 'mac',
    gltfPath: '/models/macbook-pro-m3-14.gltf',
    thumbnailPath: '/thumbnails/macbook-pro-m3-14.png',
    screenAspect: 16 / 10,
    modelScale: 0.2456,
    camPresets: MAC_CAM,
    colors: [
      { id: 'space',  label: 'Space Black', hex: '#1c1c1e' },
      { id: 'silver', label: 'Silver',      hex: '#e8e4de' },
    ],
  },
  {
    id: 'macbook-pro-m1-16',
    name: 'MacBook Pro M1 16"',
    category: 'mac',
    gltfPath: '/models/macbook-pro-m1-16.gltf',
    thumbnailPath: '/thumbnails/macbook-pro-m1-16.png',
    screenAspect: 16 / 10,
    modelScale: 3.5,
    camPresets: MAC_CAM,
    colors: [
      { id: 'space',  label: 'Space Gray', hex: '#3a3a3c' },
      { id: 'silver', label: 'Silver',     hex: '#e8e4de' },
    ],
  },
  {
    id: 'macbook-air-m2-15',
    name: 'MacBook Air M2 15"',
    category: 'mac',
    gltfPath: '/models/macbook-air-m2-15.gltf',
    thumbnailPath: '/thumbnails/macbook-air-m1.png',
    screenAspect: 16 / 10,
    modelScale: 0.2456,
    camPresets: MAC_CAM,
    colors: [
      { id: 'midnight',  label: 'Midnight',  hex: '#1c1c1e' },
      { id: 'starlight', label: 'Starlight', hex: '#f5f0e8' },
      { id: 'space',     label: 'Space Gray',hex: '#3a3a3c' },
      { id: 'silver',    label: 'Silver',    hex: '#e8e4de' },
    ],
  },
  {
    id: 'macbook-air-m2-13',
    name: 'MacBook Air M2 13"',
    category: 'mac',
    gltfPath: '/models/macbook-air-m2-13.gltf',
    thumbnailPath: '/thumbnails/macbook-air-m1.png',
    screenAspect: 16 / 10,
    modelScale: 24.56,
    camPresets: MAC_CAM,
    colors: [
      { id: 'midnight',  label: 'Midnight',  hex: '#1c1c1e' },
      { id: 'starlight', label: 'Starlight', hex: '#f5f0e8' },
      { id: 'space',     label: 'Space Gray',hex: '#3a3a3c' },
      { id: 'silver',    label: 'Silver',    hex: '#e8e4de' },
    ],
  },
  {
    id: 'macbook-air-m1',
    name: 'MacBook Air M1',
    category: 'mac',
    gltfPath: '/models/macbook-air-m1.gltf',
    thumbnailPath: '/thumbnails/macbook-air-m1.png',
    screenAspect: 16 / 10,
    modelScale: 3.5,
    camPresets: MAC_CAM,
    colors: [
      { id: 'space',     label: 'Space Gray', hex: '#3a3a3c' },
      { id: 'gold',      label: 'Gold',       hex: '#f5e6c8' },
      { id: 'silver',    label: 'Silver',     hex: '#e8e4de' },
    ],
  },
  {
    id: 'imac-24',
    name: 'iMac 24"',
    category: 'mac',
    gltfPath: '/models/imac-24.gltf',
    thumbnailPath: '/thumbnails/imac-24.png',
    screenAspect: 16 / 9,
    modelScale: 3.5,
    camPresets: {
      front:     [0, 0, 26] as [number,number,number],
      isometric: [10, 4, 22] as [number,number,number],
      side:      [26, 2, 12] as [number,number,number],
    },
    colors: [
      { id: 'silver', label: 'Silver', hex: '#e8e4de' },
      { id: 'blue',   label: 'Blue',   hex: '#4a6b8c' },
      { id: 'green',  label: 'Green',  hex: '#4a7a5a' },
      { id: 'pink',   label: 'Pink',   hex: '#f4a7b9' },
      { id: 'yellow', label: 'Yellow', hex: '#f5e066' },
      { id: 'orange', label: 'Orange', hex: '#f5a04a' },
      { id: 'purple', label: 'Purple', hex: '#6a3d8a' },
    ],
  },
  {
    id: 'surface-laptop-4',
    name: 'Surface Laptop 4',
    category: 'mac',
    gltfPath: '/models/surface-laptop-4.gltf',
    thumbnailPath: '/thumbnails/surface-laptop-4.png',
    screenAspect: 3 / 2,
    modelScale: 3.5,
    camPresets: MAC_CAM,
    colors: [
      { id: 'platinum', label: 'Platinum', hex: '#c8c8c8' },
      { id: 'black',    label: 'Matte Black',hex: '#1c1c1e' },
      { id: 'blue',     label: 'Ice Blue',  hex: '#4a6b8c' },
      { id: 'sand',     label: 'Sandstone', hex: '#c5a882' },
    ],
  },

  // ── Watches ───────────────────────────────────────────────────────────────────
  {
    id: 'watch-ultra-2',
    name: 'Apple Watch Ultra 2',
    category: 'watch',
    gltfPath: '/models/watch-ultra-2.gltf',
    thumbnailPath: '/thumbnails/watch-ultra-2.png',
    screenAspect: 1,
    modelScale: 0.425,
    camPresets: WATCH_CAM,
    colors: [
      { id: 'natural', label: 'Natural Titanium', hex: '#c8c8c8' },
      { id: 'black',   label: 'Black Titanium',   hex: '#2c2c2e' },
    ],
  },
  {
    id: 'watch-series-7',
    name: 'Apple Watch Series 7',
    category: 'watch',
    gltfPath: '/models/watch-series-7.gltf',
    thumbnailPath: '/thumbnails/watch-series-7.png',
    screenAspect: 1,
    modelScale: 3.5,
    camPresets: WATCH_CAM,
    colors: [
      { id: 'midnight',  label: 'Midnight',  hex: '#1c1c1e' },
      { id: 'starlight', label: 'Starlight', hex: '#f5f0e8' },
      { id: 'green',     label: 'Green',     hex: '#4a7a5a' },
      { id: 'blue',      label: 'Blue',      hex: '#2d5a8e' },
      { id: 'red',       label: 'Red',       hex: '#e02020' },
    ],
  },
  {
    id: 'watch-series-6',
    name: 'Apple Watch Series 6',
    category: 'watch',
    gltfPath: '/models/watch-series-6.gltf',
    thumbnailPath: '/thumbnails/watch-series-6.png',
    screenAspect: 1,
    modelScale: 3.5,
    camPresets: WATCH_CAM,
    colors: [
      { id: 'space',  label: 'Space Gray', hex: '#3a3a3c' },
      { id: 'silver', label: 'Silver',     hex: '#e8e4de' },
      { id: 'gold',   label: 'Gold',       hex: '#f5e6c8' },
      { id: 'blue',   label: 'Blue',       hex: '#2d5a8e' },
      { id: 'red',    label: 'Red',        hex: '#e02020' },
    ],
  },

  // ── Android / Generic ─────────────────────────────────────────────────────────
  {
    id: 'samsung-s21',
    name: 'Samsung Galaxy S21',
    category: 'android',
    gltfPath: '/models/samsung-s21.gltf',
    thumbnailPath: '/thumbnails/samsung-s21.png',
    screenAspect: 20 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'phantom-black',  label: 'Phantom Black',  hex: '#1c1c1e' },
      { id: 'phantom-white',  label: 'Phantom White',  hex: '#f5f0e8' },
      { id: 'phantom-gray',   label: 'Phantom Gray',   hex: '#3a3a3c' },
      { id: 'phantom-violet', label: 'Phantom Violet', hex: '#6a3d8a' },
      { id: 'phantom-pink',   label: 'Phantom Pink',   hex: '#f4a7b9' },
    ],
  },
  {
    id: 'generic-phone-thin-bezel',
    name: 'Generic Phone (Thin Bezel)',
    category: 'generic',
    gltfPath: '/models/generic-phone-thin-bezel.gltf',
    thumbnailPath: '/thumbnails/generic-phone-thin-bezel.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'black', label: 'Black', hex: '#1c1c1e' },
      { id: 'white', label: 'White', hex: '#f5f0e8' },
      { id: 'gray',  label: 'Gray',  hex: '#3a3a3c' },
    ],
  },
  {
    id: 'glass-phone',
    name: 'Glass Phone',
    category: 'generic',
    gltfPath: '/models/glass-phone.gltf',
    thumbnailPath: '/thumbnails/glass-phone.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'black', label: 'Black', hex: '#1c1c1e' },
      { id: 'white', label: 'White', hex: '#f5f0e8' },
    ],
  },
  {
    id: 'phone-display',
    name: 'Phone Display',
    category: 'generic',
    gltfPath: '/models/phone-display.gltf',
    thumbnailPath: '/thumbnails/phone-display.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'black', label: 'Black', hex: '#1c1c1e' },
      { id: 'white', label: 'White', hex: '#f5f0e8' },
      { id: 'gray',  label: 'Gray',  hex: '#3a3a3c' },
    ],
  },
]

export const DEVICE_MODELS: Record<DeviceId, DeviceModel> = Object.fromEntries(
  DEVICES.map((d) => [d.id, d])
) as Record<DeviceId, DeviceModel>

export const DEVICE_LIST: DeviceModel[] = DEVICES

export const DEVICE_CATEGORIES: { id: DeviceCategory | 'all'; label: string }[] = [
  { id: 'all',     label: 'All' },
  { id: 'iphone',  label: 'iPhone' },
  { id: 'ipad',    label: 'iPad' },
  { id: 'mac',     label: 'Mac' },
  { id: 'watch',   label: 'Watch' },
  { id: 'android', label: 'Android' },
  { id: 'generic', label: 'Generic' },
]
