import type { DeviceModel, DeviceId, DeviceCategory } from '@/types'

const MAC_CAM = {
  front:     [0,  3, 16] as [number,number,number],
  isometric: [9,  6, 13] as [number,number,number],
  side:      [18, 3,  8] as [number,number,number],
}
const TABLET_CAM = {
  front:     [0, 0, 22] as [number,number,number],
  isometric: [9, 5, 18] as [number,number,number],
  side:      [22, 3, 10] as [number,number,number],
}
const WATCH_CAM = {
  front:     [0, 0, 14] as [number,number,number],
  isometric: [5, 3, 12] as [number,number,number],
  side:      [14, 2,  6] as [number,number,number],
}

type RawDevice = Omit<DeviceModel, 'gltfPath' | 'thumbnailPath'> & { id: DeviceId }

const DEVICES: DeviceModel[] = [
  // ── iPhones ──────────────────────────────────────────────────────────────────
  {
    id: 'iphone-17-pro-max',
    name: 'iPhone 17 Pro Max',
    category: 'iphone',
    gltfPath: '/models/iphone-17-pro-max.gltf',
    thumbnailPath: '/thumbnails/iphone-17-pro-max.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.4577,
    colors: [
      { id: 'natural',  label: 'Natural Titanium',  hex: '#c8b89a' },
      { id: 'black',    label: 'Black Titanium',     hex: '#2c2c2e' },
      { id: 'white',    label: 'White Titanium',     hex: '#e8e4de' },
      { id: 'desert',   label: 'Desert Titanium',    hex: '#c5a882' },
    ],
  },
  {
    id: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    category: 'iphone',
    gltfPath: '/models/iphone-16-pro-max.gltf',
    thumbnailPath: '/thumbnails/iphone-16-pro-max.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.4577,
    colors: [
      { id: 'natural',  label: 'Natural Titanium',  hex: '#c8b89a' },
      { id: 'black',    label: 'Black Titanium',     hex: '#2c2c2e' },
      { id: 'white',    label: 'White Titanium',     hex: '#e8e4de' },
      { id: 'desert',   label: 'Desert Titanium',    hex: '#c5a882' },
    ],
  },
  {
    id: 'iphone-16-pro',
    name: 'iPhone 16 Pro',
    category: 'iphone',
    gltfPath: '/models/iphone-16-pro.gltf',
    thumbnailPath: '/thumbnails/iphone-16-pro.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.4577,
    colors: [
      { id: 'natural',  label: 'Natural Titanium',  hex: '#c8b89a' },
      { id: 'black',    label: 'Black Titanium',     hex: '#2c2c2e' },
      { id: 'white',    label: 'White Titanium',     hex: '#e8e4de' },
      { id: 'desert',   label: 'Desert Titanium',    hex: '#c5a882' },
    ],
  },
  {
    id: 'iphone-16-plus',
    name: 'iPhone 16 Plus',
    category: 'iphone',
    gltfPath: '/models/iphone-16-plus.gltf',
    thumbnailPath: '/thumbnails/iphone-16-plus.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.4577,
    colors: [
      { id: 'black',      label: 'Black',          hex: '#1c1c1e' },
      { id: 'white',      label: 'White',          hex: '#f5f0e8' },
      { id: 'pink',       label: 'Pink',           hex: '#f4a7b9' },
      { id: 'teal',       label: 'Teal',           hex: '#3a7a7a' },
      { id: 'ultramarine',label: 'Ultramarine',    hex: '#2d3d8e' },
    ],
  },
  {
    id: 'iphone-16',
    name: 'iPhone 16',
    category: 'iphone',
    gltfPath: '/models/iphone-16.gltf',
    thumbnailPath: '/thumbnails/iphone-16.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.4577,
    colors: [
      { id: 'black',      label: 'Black',          hex: '#1c1c1e' },
      { id: 'white',      label: 'White',          hex: '#f5f0e8' },
      { id: 'pink',       label: 'Pink',           hex: '#f4a7b9' },
      { id: 'teal',       label: 'Teal',           hex: '#3a7a7a' },
      { id: 'ultramarine',label: 'Ultramarine',    hex: '#2d3d8e' },
    ],
  },
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    category: 'iphone',
    gltfPath: '/models/iphone-15-pro.gltf',
    thumbnailPath: '/thumbnails/iphone-15-pro.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.4577,
    colors: [
      { id: 'natural', label: 'Natural Titanium', hex: '#c8b89a' },
      { id: 'black',   label: 'Black Titanium',   hex: '#2c2c2e' },
      { id: 'white',   label: 'White Titanium',   hex: '#e8e4de' },
      { id: 'blue',    label: 'Blue Titanium',     hex: '#4a6b8c' },
    ],
  },
  {
    id: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    category: 'iphone',
    gltfPath: '/models/iphone-15-pro-max.gltf',
    thumbnailPath: '/thumbnails/iphone-15-pro-max.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.4577,
    colors: [
      { id: 'natural', label: 'Natural Titanium', hex: '#c8b89a' },
      { id: 'black',   label: 'Black Titanium',   hex: '#2c2c2e' },
      { id: 'white',   label: 'White Titanium',   hex: '#e8e4de' },
      { id: 'blue',    label: 'Blue Titanium',     hex: '#4a6b8c' },
    ],
  },
  {
    id: 'iphone-15',
    name: 'iPhone 15',
    category: 'iphone',
    gltfPath: '/models/iphone-15.gltf',
    thumbnailPath: '/thumbnails/iphone-15.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.4577,
    colors: [
      { id: 'black',  label: 'Black',  hex: '#1c1c1e' },
      { id: 'blue',   label: 'Blue',   hex: '#4a90a4' },
      { id: 'green',  label: 'Green',  hex: '#5a8a6a' },
      { id: 'yellow', label: 'Yellow', hex: '#f5e066' },
      { id: 'pink',   label: 'Pink',   hex: '#f4a7b9' },
    ],
  },
  {
    id: 'iphone-15-plus',
    name: 'iPhone 15 Plus',
    category: 'iphone',
    gltfPath: '/models/iphone-15-plus.gltf',
    thumbnailPath: '/thumbnails/iphone-15-plus.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.4577,
    colors: [
      { id: 'black',  label: 'Black',  hex: '#1c1c1e' },
      { id: 'blue',   label: 'Blue',   hex: '#4a90a4' },
      { id: 'green',  label: 'Green',  hex: '#5a8a6a' },
      { id: 'yellow', label: 'Yellow', hex: '#f5e066' },
      { id: 'pink',   label: 'Pink',   hex: '#f4a7b9' },
    ],
  },
  {
    id: 'iphone-14-pro',
    name: 'iPhone 14 Pro',
    category: 'iphone',
    gltfPath: '/models/iphone-14-pro.gltf',
    thumbnailPath: '/thumbnails/iphone-14-pro.png',
    screenAspect: 19.5 / 9,
    modelScale: 47.47,
    colors: [
      { id: 'space',  label: 'Space Black',  hex: '#1c1c1e' },
      { id: 'silver', label: 'Silver',        hex: '#e8e4de' },
      { id: 'gold',   label: 'Gold',          hex: '#f5e6c8' },
      { id: 'purple', label: 'Deep Purple',   hex: '#4a3d6b' },
    ],
  },
  {
    id: 'iphone-13-pro-max',
    name: 'iPhone 13 Pro Max',
    category: 'iphone',
    gltfPath: '/models/iphone-13-pro-max.gltf',
    thumbnailPath: '/thumbnails/iphone-13-pro-max.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'graphite', label: 'Graphite',    hex: '#3a3a3c' },
      { id: 'gold',     label: 'Gold',        hex: '#f5e6c8' },
      { id: 'silver',   label: 'Silver',      hex: '#e8e4de' },
      { id: 'sierra',   label: 'Sierra Blue', hex: '#8fa8c0' },
      { id: 'alpine',   label: 'Alpine Green',hex: '#4a7a5a' },
    ],
  },
  {
    id: 'iphone-13',
    name: 'iPhone 13',
    category: 'iphone',
    gltfPath: '/models/iphone-13.gltf',
    thumbnailPath: '/thumbnails/iphone-13.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'midnight',  label: 'Midnight',  hex: '#1c1c1e' },
      { id: 'starlight', label: 'Starlight', hex: '#f5f0e8' },
      { id: 'blue',      label: 'Blue',      hex: '#2d5a8e' },
      { id: 'pink',      label: 'Pink',      hex: '#f4a7b9' },
      { id: 'green',     label: 'Green',     hex: '#4a7a5a' },
      { id: 'red',       label: 'Red',       hex: '#e02020' },
    ],
  },
  {
    id: 'iphone-13-mini',
    name: 'iPhone 13 mini',
    category: 'iphone',
    gltfPath: '/models/iphone-13-mini.gltf',
    thumbnailPath: '/thumbnails/iphone-13-mini.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'midnight',  label: 'Midnight',  hex: '#1c1c1e' },
      { id: 'starlight', label: 'Starlight', hex: '#f5f0e8' },
      { id: 'blue',      label: 'Blue',      hex: '#2d5a8e' },
      { id: 'pink',      label: 'Pink',      hex: '#f4a7b9' },
      { id: 'green',     label: 'Green',     hex: '#4a7a5a' },
      { id: 'red',       label: 'Red',       hex: '#e02020' },
    ],
  },
  {
    id: 'iphone-12-pro-bezel-less',
    name: 'iPhone 12 Pro (Bezel-less)',
    category: 'iphone',
    gltfPath: '/models/iphone-12-pro-bezel-less.gltf',
    thumbnailPath: '/thumbnails/iphone-12-pro-bezel-less.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'graphite', label: 'Graphite', hex: '#3a3a3c' },
      { id: 'silver',   label: 'Silver',   hex: '#e8e4de' },
      { id: 'gold',     label: 'Gold',     hex: '#f5e6c8' },
      { id: 'blue',     label: 'Blue',     hex: '#2d5a8e' },
    ],
  },
  {
    id: 'iphone-12-2020',
    name: 'iPhone 12 (2020)',
    category: 'iphone',
    gltfPath: '/models/iphone-12-2020.gltf',
    thumbnailPath: '/thumbnails/iphone-12-2020.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'black',  label: 'Black',  hex: '#1c1c1e' },
      { id: 'white',  label: 'White',  hex: '#f5f0e8' },
      { id: 'red',    label: 'Red',    hex: '#e02020' },
      { id: 'green',  label: 'Green',  hex: '#4a7a5a' },
      { id: 'blue',   label: 'Blue',   hex: '#2d5a8e' },
      { id: 'purple', label: 'Purple', hex: '#6a3d8a' },
    ],
  },
  {
    id: 'iphone-12-pro',
    name: 'iPhone 12 Pro',
    category: 'iphone',
    gltfPath: '/models/iphone-12-pro.gltf',
    thumbnailPath: '/thumbnails/iphone-12-pro.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.6285,
    colors: [
      { id: 'graphite', label: 'Graphite', hex: '#3a3a3c' },
      { id: 'silver',   label: 'Silver',   hex: '#e8e4de' },
      { id: 'gold',     label: 'Gold',     hex: '#f5e6c8' },
      { id: 'blue',     label: 'Pacific Blue', hex: '#2d5a8e' },
    ],
  },
  {
    id: 'iphone-11-pro',
    name: 'iPhone 11 Pro',
    category: 'iphone',
    gltfPath: '/models/iphone-11-pro.gltf',
    thumbnailPath: '/thumbnails/iphone-11-pro.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.6945,
    colors: [
      { id: 'space',    label: 'Space Gray',    hex: '#3a3a3c' },
      { id: 'silver',   label: 'Silver',         hex: '#e8e4de' },
      { id: 'gold',     label: 'Gold',           hex: '#f5e6c8' },
      { id: 'midnight', label: 'Midnight Green', hex: '#4a5a4a' },
    ],
  },
  {
    id: 'iphone-8',
    name: 'iPhone 8',
    category: 'iphone',
    gltfPath: '/models/iphone-8.gltf',
    thumbnailPath: '/thumbnails/iphone-8.png',
    screenAspect: 16 / 9,
    modelScale: 0.7223,
    colors: [
      { id: 'space',  label: 'Space Gray', hex: '#3a3a3c' },
      { id: 'silver', label: 'Silver',     hex: '#e8e4de' },
      { id: 'gold',   label: 'Gold',       hex: '#f5e6c8' },
    ],
  },
  {
    id: '9-pro',
    name: '9 Pro',
    category: 'iphone',
    gltfPath: '/models/9-pro.gltf',
    thumbnailPath: '/thumbnails/9-pro.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.6058,
    colors: [
      { id: 'black',   label: 'Black',   hex: '#1c1c1e' },
      { id: 'silver',  label: 'Silver',  hex: '#e8e4de' },
      { id: 'gold',    label: 'Gold',    hex: '#f5e6c8' },
    ],
  },
  {
    id: 'pro-max-notchless',
    name: 'Pro Max Notchless',
    category: 'iphone',
    gltfPath: '/models/pro-max-notchless.gltf',
    thumbnailPath: '/thumbnails/pro-max-notchless.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'black',   label: 'Black',          hex: '#1c1c1e' },
      { id: 'silver',  label: 'Silver',          hex: '#e8e4de' },
      { id: 'natural', label: 'Natural Titanium',hex: '#c8b89a' },
    ],
  },

  // ── iPads ─────────────────────────────────────────────────────────────────────
  {
    id: 'ipad-pro-11',
    name: 'iPad Pro 11"',
    category: 'ipad',
    gltfPath: '/models/ipad-pro-11.gltf',
    thumbnailPath: '/thumbnails/ipad-pro-11.png',
    screenAspect: 4 / 3,
    modelScale: 0.2973,
    camPresets: TABLET_CAM,
    colors: [
      { id: 'space',  label: 'Space Gray', hex: '#2c2c2e' },
      { id: 'silver', label: 'Silver',     hex: '#e8e4de' },
    ],
  },
  {
    id: 'ipad-m1-2021',
    name: 'iPad M1 (2021)',
    category: 'ipad',
    gltfPath: '/models/ipad-m1-2021.gltf',
    thumbnailPath: '/thumbnails/ipad-m1-2021.png',
    screenAspect: 4 / 3,
    modelScale: 0.3557,
    camPresets: TABLET_CAM,
    colors: [
      { id: 'space',  label: 'Space Gray', hex: '#2c2c2e' },
      { id: 'silver', label: 'Silver',     hex: '#e8e4de' },
    ],
  },
  {
    id: 'ipad-mini-6',
    name: 'iPad mini 6',
    category: 'ipad',
    gltfPath: '/models/ipad-mini-6.gltf',
    thumbnailPath: '/thumbnails/ipad-mini-6.png',
    screenAspect: 3 / 2,
    modelScale: 40.8,
    camPresets: TABLET_CAM,
    colors: [
      { id: 'space',     label: 'Space Gray', hex: '#2c2c2e' },
      { id: 'starlight', label: 'Starlight',  hex: '#f5f0e8' },
      { id: 'pink',      label: 'Pink',       hex: '#f4a7b9' },
      { id: 'purple',    label: 'Purple',     hex: '#6a3d8a' },
    ],
  },
  {
    id: 'ipad-2021-magic-keyboard',
    name: 'iPad 2021 + Magic Keyboard',
    category: 'ipad',
    gltfPath: '/models/ipad-2021-magic-keyboard.gltf',
    thumbnailPath: '/thumbnails/ipad-2021-magic-keyboard.png',
    screenAspect: 4 / 3,
    modelScale: 35.1,
    camPresets: MAC_CAM,
    colors: [
      { id: 'space',     label: 'Space Gray', hex: '#2c2c2e' },
      { id: 'silver',    label: 'Silver',     hex: '#e8e4de' },
    ],
  },
  {
    id: 'generic-tablet',
    name: 'Generic Tablet',
    category: 'ipad',
    gltfPath: '/models/generic-tablet.gltf',
    thumbnailPath: '/thumbnails/generic-tablet.png',
    screenAspect: 4 / 3,
    modelScale: 0.1157,
    camPresets: TABLET_CAM,
    colors: [
      { id: 'black', label: 'Black', hex: '#1c1c1e' },
      { id: 'white', label: 'White', hex: '#f5f0e8' },
    ],
  },
  {
    id: 'infinity-tablet',
    name: 'Infinity Tablet',
    category: 'ipad',
    gltfPath: '/models/infinity-tablet.gltf',
    thumbnailPath: '/thumbnails/infinity-tablet.png',
    screenAspect: 4 / 3,
    modelScale: 0.1157,
    camPresets: TABLET_CAM,
    colors: [
      { id: 'black', label: 'Black', hex: '#1c1c1e' },
      { id: 'white', label: 'White', hex: '#f5f0e8' },
    ],
  },

  // ── Macs ──────────────────────────────────────────────────────────────────────
  {
    id: 'macbook-pro-m3-16',
    name: 'MacBook Pro M3 16"',
    category: 'mac',
    gltfPath: '/models/macbook-pro-m3-16.gltf',
    thumbnailPath: '/thumbnails/macbook-pro-m3-16.png',
    screenAspect: 16 / 10,
    modelScale: 0.2811,
    camPresets: MAC_CAM,
    colors: [
      { id: 'space',  label: 'Space Black', hex: '#1c1c1e' },
      { id: 'silver', label: 'Silver',      hex: '#e8e4de' },
    ],
  },
  {
    id: 'macbook-pro-m3-14',
    name: 'MacBook Pro M3 14"',
    category: 'mac',
    gltfPath: '/models/macbook-pro-m3-14.gltf',
    thumbnailPath: '/thumbnails/macbook-pro-m3-14.png',
    screenAspect: 16 / 10,
    modelScale: 0.3199,
    camPresets: MAC_CAM,
    colors: [
      { id: 'space',  label: 'Space Black', hex: '#1c1c1e' },
      { id: 'silver', label: 'Silver',      hex: '#e8e4de' },
    ],
  },
  {
    id: 'macbook-pro-m1-16',
    name: 'MacBook Pro M1 16"',
    category: 'mac',
    gltfPath: '/models/macbook-pro-m1-16.gltf',
    thumbnailPath: '/thumbnails/macbook-pro-m1-16.png',
    screenAspect: 16 / 10,
    modelScale: 0.2811,
    camPresets: MAC_CAM,
    colors: [
      { id: 'space',  label: 'Space Gray', hex: '#3a3a3c' },
      { id: 'silver', label: 'Silver',     hex: '#e8e4de' },
    ],
  },
  {
    id: 'macbook-air-m2-15',
    name: 'MacBook Air M2 15"',
    category: 'mac',
    gltfPath: '/models/macbook-air-m2-15.gltf',
    thumbnailPath: '/thumbnails/macbook-pro-m3-16.png',
    screenAspect: 16 / 10,
    modelScale: 0.2938,
    camPresets: MAC_CAM,
    colors: [
      { id: 'starlight', label: 'Starlight', hex: '#f5f0e8' },
      { id: 'midnight',  label: 'Midnight',  hex: '#2c2c2e' },
      { id: 'space',     label: 'Space Gray',hex: '#3a3a3c' },
      { id: 'silver',    label: 'Silver',    hex: '#e8e4de' },
    ],
  },
  {
    id: 'macbook-air-m2-13',
    name: 'MacBook Air M2 13"',
    category: 'mac',
    gltfPath: '/models/macbook-air-m2-13.gltf',
    thumbnailPath: '/thumbnails/macbook-pro-m3-14.png',
    screenAspect: 16 / 10,
    modelScale: 0.3288,
    camPresets: MAC_CAM,
    colors: [
      { id: 'starlight', label: 'Starlight', hex: '#f5f0e8' },
      { id: 'midnight',  label: 'Midnight',  hex: '#2c2c2e' },
      { id: 'space',     label: 'Space Gray',hex: '#3a3a3c' },
      { id: 'silver',    label: 'Silver',    hex: '#e8e4de' },
    ],
  },
  {
    id: 'macbook-air-m1',
    name: 'MacBook Air M1',
    category: 'mac',
    gltfPath: '/models/macbook-air-m1.gltf',
    thumbnailPath: '/thumbnails/macbook-air-m1.png',
    screenAspect: 16 / 10,
    modelScale: 0.3288,
    camPresets: MAC_CAM,
    colors: [
      { id: 'space',     label: 'Space Gray', hex: '#3a3a3c' },
      { id: 'gold',      label: 'Gold',       hex: '#f5e6c8' },
      { id: 'silver',    label: 'Silver',     hex: '#e8e4de' },
    ],
  },
  {
    id: 'imac-24',
    name: 'iMac 24"',
    category: 'mac',
    gltfPath: '/models/imac-24.gltf',
    thumbnailPath: '/thumbnails/imac-24.png',
    screenAspect: 16 / 9,
    modelScale: 6.0,
    camPresets: {
      front:     [0, 0, 26] as [number,number,number],
      isometric: [10, 4, 22] as [number,number,number],
      side:      [26, 2, 12] as [number,number,number],
    },
    colors: [
      { id: 'silver', label: 'Silver', hex: '#e8e4de' },
      { id: 'blue',   label: 'Blue',   hex: '#4a6b8c' },
      { id: 'green',  label: 'Green',  hex: '#4a7a5a' },
      { id: 'pink',   label: 'Pink',   hex: '#f4a7b9' },
      { id: 'yellow', label: 'Yellow', hex: '#f5e066' },
      { id: 'orange', label: 'Orange', hex: '#f5a04a' },
      { id: 'purple', label: 'Purple', hex: '#6a3d8a' },
    ],
  },
  {
    id: 'macbook-16',
    name: 'MacBook 16"',
    category: 'mac',
    gltfPath: '/models/macbook-16.gltf',
    thumbnailPath: '/thumbnails/macbook-16.png',
    screenAspect: 16 / 10,
    modelScale: 0.0205,
    camPresets: MAC_CAM,
    colors: [
      { id: 'space',  label: 'Space Gray', hex: '#3a3a3c' },
      { id: 'silver', label: 'Silver',     hex: '#e8e4de' },
    ],
  },
  {
    id: 'macbook-air-2018',
    name: 'MacBook Air (2018)',
    category: 'mac',
    gltfPath: '/models/macbook-air-2018.gltf',
    thumbnailPath: '/thumbnails/macbook-air-2018.png',
    screenAspect: 16 / 10,
    modelScale: 0.0205,
    camPresets: MAC_CAM,
    colors: [
      { id: 'space',  label: 'Space Gray', hex: '#3a3a3c' },
      { id: 'gold',   label: 'Gold',       hex: '#f5e6c8' },
      { id: 'silver', label: 'Silver',     hex: '#e8e4de' },
    ],
  },
  {
    id: 'xdr-2019',
    name: 'Pro Display XDR',
    category: 'mac',
    gltfPath: '/models/xdr-2019.gltf',
    thumbnailPath: '/thumbnails/xdr-2019.png',
    screenAspect: 16 / 9,
    modelScale: 0.1397,
    camPresets: {
      front:     [0, 0, 26] as [number,number,number],
      isometric: [10, 4, 22] as [number,number,number],
      side:      [26, 2, 12] as [number,number,number],
    },
    colors: [
      { id: 'silver', label: 'Silver', hex: '#e8e4de' },
    ],
  },
  {
    id: 'surface-laptop-4',
    name: 'Surface Laptop 4',
    category: 'mac',
    gltfPath: '/models/surface-laptop-4.gltf',
    thumbnailPath: '/thumbnails/surface-laptop-4.png',
    screenAspect: 3 / 2,
    modelScale: 39.0,
    camPresets: MAC_CAM,
    colors: [
      { id: 'platinum', label: 'Platinum', hex: '#c8c8c8' },
      { id: 'black',    label: 'Matte Black',hex: '#1c1c1e' },
      { id: 'blue',     label: 'Ice Blue',  hex: '#4a6b8c' },
      { id: 'sand',     label: 'Sandstone', hex: '#c5a882' },
    ],
  },

  // ── Watches ───────────────────────────────────────────────────────────────────
  {
    id: 'watch-ultra-2',
    name: 'Apple Watch Ultra 2',
    category: 'watch',
    gltfPath: '/models/watch-ultra-2.gltf',
    thumbnailPath: '/thumbnails/watch-ultra-2.png',
    screenAspect: 1,
    modelScale: 0.52,
    camPresets: WATCH_CAM,
    colors: [
      { id: 'natural', label: 'Natural Titanium', hex: '#c8c8c8' },
      { id: 'black',   label: 'Black Titanium',   hex: '#2c2c2e' },
    ],
  },
  {
    id: 'watch-series-7',
    name: 'Apple Watch Series 7',
    category: 'watch',
    gltfPath: '/models/watch-series-7.gltf',
    thumbnailPath: '/thumbnails/watch-series-7.png',
    screenAspect: 1,
    modelScale: 3.15,
    camPresets: WATCH_CAM,
    colors: [
      { id: 'midnight',  label: 'Midnight',  hex: '#1c1c1e' },
      { id: 'starlight', label: 'Starlight', hex: '#f5f0e8' },
      { id: 'green',     label: 'Green',     hex: '#4a7a5a' },
      { id: 'blue',      label: 'Blue',      hex: '#2d5a8e' },
      { id: 'red',       label: 'Red',       hex: '#e02020' },
    ],
  },
  {
    id: 'watch-series-6',
    name: 'Apple Watch Series 6',
    category: 'watch',
    gltfPath: '/models/watch-series-6.gltf',
    thumbnailPath: '/thumbnails/watch-series-6.png',
    screenAspect: 1,
    modelScale: 3.15,
    camPresets: WATCH_CAM,
    colors: [
      { id: 'space',  label: 'Space Gray', hex: '#3a3a3c' },
      { id: 'silver', label: 'Silver',     hex: '#e8e4de' },
      { id: 'gold',   label: 'Gold',       hex: '#f5e6c8' },
      { id: 'blue',   label: 'Blue',       hex: '#2d5a8e' },
      { id: 'red',    label: 'Red',        hex: '#e02020' },
    ],
  },
  {
    id: 'apple-watch-4',
    name: 'Apple Watch Series 4',
    category: 'watch',
    gltfPath: '/models/apple-watch-4.gltf',
    thumbnailPath: '/thumbnails/apple-watch-4.png',
    screenAspect: 1,
    modelScale: 0.4094,
    camPresets: WATCH_CAM,
    colors: [
      { id: 'space',  label: 'Space Gray', hex: '#3a3a3c' },
      { id: 'silver', label: 'Silver',     hex: '#e8e4de' },
      { id: 'gold',   label: 'Gold',       hex: '#f5e6c8' },
    ],
  },

  // ── Android / Generic ─────────────────────────────────────────────────────────
  {
    id: 'galaxy-s25-plus',
    name: 'Samsung Galaxy S25+',
    category: 'android',
    gltfPath: '/models/galaxy-s25-plus.gltf',
    thumbnailPath: '/thumbnails/galaxy-s25-plus.png',
    screenAspect: 19.5 / 9,
    modelScale: 44.2,
    colors: [
      { id: 'titanium-silver',  label: 'Titanium Silverblue', hex: '#8fa8c0' },
      { id: 'titanium-black',   label: 'Titanium Black',      hex: '#1c1c1e' },
      { id: 'titanium-white',   label: 'Titanium White',      hex: '#e8e4de' },
      { id: 'titanium-jade',    label: 'Titanium Jade',       hex: '#4a7a6a' },
    ],
  },
  {
    id: 'galaxy-s25',
    name: 'Samsung Galaxy S25',
    category: 'android',
    gltfPath: '/models/galaxy-s25.gltf',
    thumbnailPath: '/thumbnails/galaxy-s25.png',
    screenAspect: 19.5 / 9,
    modelScale: 47.6,
    colors: [
      { id: 'titanium-silver',  label: 'Titanium Silverblue', hex: '#8fa8c0' },
      { id: 'titanium-black',   label: 'Titanium Black',      hex: '#1c1c1e' },
      { id: 'titanium-white',   label: 'Titanium White',      hex: '#e8e4de' },
      { id: 'titanium-mint',    label: 'Titanium Mint',       hex: '#7abda0' },
    ],
  },
  {
    id: 'samsung-s21',
    name: 'Samsung Galaxy S21',
    category: 'android',
    gltfPath: '/models/samsung-s21.gltf',
    thumbnailPath: '/thumbnails/samsung-s21.png',
    screenAspect: 20 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'phantom-black',  label: 'Phantom Black',  hex: '#1c1c1e' },
      { id: 'phantom-white',  label: 'Phantom White',  hex: '#f5f0e8' },
      { id: 'phantom-gray',   label: 'Phantom Gray',   hex: '#3a3a3c' },
      { id: 'phantom-violet', label: 'Phantom Violet', hex: '#6a3d8a' },
      { id: 'phantom-pink',   label: 'Phantom Pink',   hex: '#f4a7b9' },
    ],
  },
  {
    id: 'pixel-4a',
    name: 'Google Pixel 4a',
    category: 'android',
    gltfPath: '/models/pixel-4a.gltf',
    thumbnailPath: '/thumbnails/pixel-4a.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.6954,
    colors: [
      { id: 'black', label: 'Just Black', hex: '#1c1c1e' },
      { id: 'white', label: 'Barely Blue', hex: '#e8eaf0' },
    ],
  },
  {
    id: 'galaxy-s9',
    name: 'Samsung Galaxy S9',
    category: 'android',
    gltfPath: '/models/galaxy-s9.gltf',
    thumbnailPath: '/thumbnails/galaxy-s9.png',
    screenAspect: 18.5 / 9,
    modelScale: 0.8396,
    colors: [
      { id: 'midnight', label: 'Midnight Black', hex: '#1c1c1e' },
      { id: 'coral',    label: 'Coral Blue',     hex: '#4a6b8c' },
      { id: 'lilac',    label: 'Lilac Purple',   hex: '#8a6b9a' },
      { id: 'titanium', label: 'Titanium Gray',   hex: '#8a8a8e' },
    ],
  },
  {
    id: 'generic-phone-thin-bezel',
    name: 'Generic Phone (Thin Bezel)',
    category: 'generic',
    gltfPath: '/models/generic-phone-thin-bezel.gltf',
    thumbnailPath: '/thumbnails/generic-phone-thin-bezel.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'black', label: 'Black', hex: '#1c1c1e' },
      { id: 'white', label: 'White', hex: '#f5f0e8' },
      { id: 'gray',  label: 'Gray',  hex: '#3a3a3c' },
    ],
  },
  {
    id: 'glass-phone',
    name: 'Glass Phone',
    category: 'generic',
    gltfPath: '/models/glass-phone.gltf',
    thumbnailPath: '/thumbnails/glass-phone.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'black', label: 'Black', hex: '#1c1c1e' },
      { id: 'white', label: 'White', hex: '#f5f0e8' },
    ],
  },
  {
    id: 'phone-display',
    name: 'Phone Display',
    category: 'generic',
    gltfPath: '/models/phone-display.gltf',
    thumbnailPath: '/thumbnails/phone-display.png',
    screenAspect: 19.5 / 9,
    modelScale: 3.5,
    colors: [
      { id: 'black', label: 'Black', hex: '#1c1c1e' },
      { id: 'white', label: 'White', hex: '#f5f0e8' },
      { id: 'gray',  label: 'Gray',  hex: '#3a3a3c' },
    ],
  },
  {
    id: 'clean-phone',
    name: 'CleanPhone',
    category: 'generic',
    gltfPath: '/models/clean-phone.gltf',
    thumbnailPath: '/thumbnails/clean-phone.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.6238,
    colors: [
      { id: 'black', label: 'Black', hex: '#1c1c1e' },
      { id: 'white', label: 'White', hex: '#f5f0e8' },
    ],
  },
  {
    id: 'flow-3',
    name: 'Flow 3',
    category: 'generic',
    gltfPath: '/models/flow-3.gltf',
    thumbnailPath: '/thumbnails/flow-3.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.3680,
    colors: [
      { id: 'black', label: 'Black', hex: '#1c1c1e' },
      { id: 'white', label: 'White', hex: '#f5f0e8' },
    ],
  },
  {
    id: 'frame-tv',
    name: 'Samsung Frame TV',
    category: 'generic',
    gltfPath: '/models/frame-tv.gltf',
    thumbnailPath: '/thumbnails/frame-tv.png',
    screenAspect: 16 / 9,
    modelScale: 0.6429,
    camPresets: {
      front:     [0, 0, 26] as [number,number,number],
      isometric: [10, 4, 22] as [number,number,number],
      side:      [26, 2, 12] as [number,number,number],
    },
    colors: [
      { id: 'black', label: 'Black', hex: '#1c1c1e' },
      { id: 'white', label: 'White', hex: '#f5f0e8' },
    ],
  },
  {
    id: '1-device',
    name: '1 Device',
    category: 'generic',
    gltfPath: '/models/1-device.gltf',
    thumbnailPath: '/thumbnails/flow-3.png',
    screenAspect: 19.5 / 9,
    modelScale: 0.6963,
    colors: [
      { id: 'black', label: 'Black', hex: '#1c1c1e' },
      { id: 'white', label: 'White', hex: '#f5f0e8' },
    ],
  },
]

const ASSETS_BASE = (import.meta.env.VITE_ASSETS_BASE_URL as string | undefined)?.replace(/\/$/, '') ?? ''

function rebase(d: DeviceModel): DeviceModel {
  if (!ASSETS_BASE) return d
  return { ...d, gltfPath: `${ASSETS_BASE}${d.gltfPath}`, thumbnailPath: `${ASSETS_BASE}${d.thumbnailPath}` }
}

export const DEVICE_MODELS: Record<DeviceId, DeviceModel> = Object.fromEntries(
  DEVICES.map((d) => [d.id, rebase(d)])
) as Record<DeviceId, DeviceModel>

export const DEVICE_LIST: DeviceModel[] = DEVICES.map(rebase)

export const DEVICE_CATEGORIES: { id: DeviceCategory | 'all'; label: string }[] = [
  { id: 'all',     label: 'All' },
  { id: 'iphone',  label: 'iPhone' },
  { id: 'ipad',    label: 'iPad' },
  { id: 'mac',     label: 'Mac' },
  { id: 'watch',   label: 'Watch' },
  { id: 'android', label: 'Android' },
  { id: 'generic', label: 'Generic' },
]
